version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_GPU_LAYERS=50

  rag-app:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_BASE_URL=http://ollama:11434
      - EMBEDDING_MODEL=BAAI/bge-large-en-v1.5
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./docs:/app/docs
    ports:
      - "7860:7860"
    depends_on:
      ollama:
        condition: service_started

volumes:
  ollama_data: